version: "3.8"
services:
    zookeeper:
        image: zookeeper:3.4.9
        hostname: zookeeper
        ports:
        - "2181:2181"
        environment:
            ZOO_MY_ID: 1
            ZOO_PORT: 2181
            ZOO_SERVERS: server.1=zookeeper:2888:3888
        volumes:
            - ./data/zookeeper/data:/data
            - ./data/zookeeper/datalog:/datalog
        depends_on:
            - backend_api
    

    kafka1:
        image: confluentinc/cp-kafka:5.3.0
        hostname: kafka1
        ports:
            - "9091:9091"
        environment:
            KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka1:19091,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9091
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
            KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
            KAFKA_BROKER_ID: 1
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        volumes:
            - ./data/kafka1/data:/var/lib/kafka/data
        depends_on:
            - zookeeper
            - backend_api
    





    # kafka:
    #     ports:
    #     - '50001:9092'
    #     - '50002:9093'
    #     depends_on:
    #     - zookeeper
    #     environment:
    #         KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
    #         KAFKA_LISTENERS: 'INTERNAL://:9092'
    #         KAFKA_ADVERTISED_LISTENERS: 'INTERNAL://:9092'
    #         KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'INTERNAL:PLAINTEXT'
    #         KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
    #         KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: '1'
    #         KAFKA_CREATE_TOPICS: 'example-topic:1:1'
    #         KAFKA_ADVERTISED_HOST_NAME: host.docker.internal # change to 172.17.0.1 if running on Ubuntu
    #     image: 'wurstmeister/kafka:2.13-2.8.1'
    #     volumes:
    #     - '/var/run/docker.sock:/var/run/docker.sock'
    # publisher:
    #     depends_on:
    #     - kafka
    #     environment:
    #         TOPIC: example-topic
    #         ENVIRONMENT: local
    #         INTERNAL_KAFKA_ADDR: 'kafka:9092'
    #     build:
    #         context: ./publisher
    # subscriber:
    #     depends_on:
    #     - kafka
    #     environment:
    #         TOPIC: example-topic
    #         ENVIRONMENT: local
    #         INTERNAL_KAFKA_ADDR: 'kafka:9092'
    #     build:
    #         context: ./subscriber
    # volumes: {}







    backend_orders:
        build:
            dockerfile: ./backend_orders/Dockerfile
        ports:
            - "8001:8001"
            - "9091:9091"
    
    backend_api:
        build:
            dockerfile: ./backend_api/django_proyect/Dockerfile
        ports:
            - "8000:8000"
            - "9092:9092"
        # command: ["python3 manage.py makemigrations", "python3 manage.py runserver 0.0.0.0:8000"]
        command: "python3 manage.py runserver 0.0.0.0:8000"
    




