version: "3.8"
services:
    # zookeeper:
    #     image: zookeeper:3.4.9
    #     hostname: zookeeper
    #     ports:
    #     - "2181:2181"
    #     environment:
    #         ZOO_MY_ID: 1
    #         ZOO_PORT: 2181
    #         ZOO_SERVERS: server.1=zookeeper:2888:3888
    #     volumes:
    #         - ./data/zookeeper/data:/data
    #         - ./data/zookeeper/datalog:/datalog










        # healthcheck:
        #     test: ["CMD-SHELL", "echo ruok | nc -w 2 zookeeper 4444"]
        #     interval: 5s
        #     timeout: 10s
        #     retries: 3

    

    # kafka1:
    #     image: confluentinc/cp-kafka:5.3.0
    #     hostname: kafka1
    #     ports:
    #         - "9091:9091"
    #     environment:
    #         KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka1:19091,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9091
    #         KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
    #         KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
    #         KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
    #         KAFKA_BROKER_ID: 1
    #         KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    #     volumes:
    #         - ./data/kafka1/data:/var/lib/kafka/data
    #     depends_on:
    #         - zookeeper
    #     healthcheck:
    #         test: nc -z localhost 9091 || exit -1
    #         start_period: 15s
    #         interval: 5s
    #         timeout: 10s
    #         retries: 10

    # backend_analytics:
    #     restart: always
    #     build:
    #         dockerfile: ./ecommerce/backend_analytics/Dockerfile
    #     ports:
    #         - "8001:8001"
    #     env_file:
    #         - .env
        # depends_on:
        #     analytics_database:
        #         condition: service_healthy
            # kafka1:
                # condition: service_healthy
        
    
    # backend_api:
    #     restart: always
    #     build:
    #         dockerfile: ./ecommerce/backend_api/Dockerfile
    #     ports:
    #         - "8000:8000"
    #     command: "python3 manage.py runserver 0.0.0.0:8000"
    #     depends_on:
    #         kafka1:
    #             condition: service_healthy
    #     volumes:
    #         - ./ecommerce/backend_api:/api

    analytics_database:
        # image: bitnami/postgresql:15.4.0-debian-11-r5
        # image: postgres:15-alpine
        build:
            dockerfile: ./ecommerce/database_analytics/Dockerfile
        restart: always
        ports:
            - '5432:5432'
        networks:
            - turreta_network
        # env_file:
        #     - .env
        volumes:
            - ./data/backend_analytics:/var/lib/analytics_db/data
        # command: /bin/bash -c "until pg_isready -U ${POSTGRES_USER} -p 5432; do sleep 1; done; psql -U ${POSTGRES_USER} -c 'CREATE DATABASE bank;'"

        environment:
            POSTGRES_USER: postgres # The PostgreSQL user (useful to connect to the database)
            POSTGRES_PASSWORD: postgres # The PostgreSQL password (useful to connect to the database)
            POSTGRES_DB: default_database # The PostgreSQL default database (automatically created at first launch)
            # DATABASE_URL: postgres://{analytics_database_username}:{analytics_database_password}@{analytics_database_host}/somedb
            # analytics_db_url: 'postgresql://{username}:{password}@{host}'
            
        # healthcheck:
        #     test: [“CMD-SHELL”, “pg_isready”]
        #     interval: 1s
        #     timeout: 5s
        #     retries: 10

            
    pgadmin:
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
            PGADMIN_DEFAULT_PASSWORD: admin
            PGADMIN_LISTEN_PORT: 80
            PGADMIN_CONFIG_SERVER_MODE: 'False'
        ports:
            - "5050:80"
        volumes:
            - pgadmin:/var/lib/pgadmin
        depends_on:
            - analytics_database
        networks:
            - turreta_network
        restart: unless-stopped

    
networks:
  turreta_network:
    driver: bridge
# volumes:
#   analytics_database:
#     driver: local
volumes:
    analytics_database:
    pgadmin:

    # personal_website:
    #     build:
    #         dockerfile: ./personal_website/Dockerfile