# Generated by Django 4.1.2 on 2024-01-29 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='Name')),
                ('hexadecimal', models.CharField(max_length=60, unique=True, verbose_name='Hexadecimal')),
            ],
        ),
        migrations.CreateModel(
            name='Discounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.CharField(max_length=60, verbose_name='Percentage')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='Name')),
                ('duration', models.CharField(max_length=60, verbose_name='Duration')),
            ],
        ),
        migrations.CreateModel(
            name='ImageFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='Image format')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=60, unique=True, verbose_name='Image path')),
                ('format_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='image_format_id', to='inventory.imageformat')),
            ],
        ),
        migrations.CreateModel(
            name='Sizes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=60, unique=True, verbose_name='Size')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=60, verbose_name='Description')),
                ('name', models.CharField(max_length=60, verbose_name='Name')),
                ('sku', models.CharField(max_length=60, unique=True, verbose_name='SKU')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_id', to='inventory.categories')),
                ('color', models.ForeignKey(max_length=60, on_delete=django.db.models.deletion.RESTRICT, to='inventory.colors')),
                ('size', models.ForeignKey(max_length=60, on_delete=django.db.models.deletion.RESTRICT, to='inventory.sizes')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='image_id', to='inventory.images')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='product_id', to='inventory.products')),
            ],
        ),
    ]
