version: '3'
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - webapp1
      - webapp2
      - kafka
    networks:
      - my_network

networks:
  my_network:
