# Generated by Django 4.2 on 2024-01-12 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='Country')),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Province name')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='province_id', to='users.country')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.CharField(editable=False, max_length=16, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=24, unique=True, verbose_name='Username')),
                ('email', models.EmailField(max_length=64, unique=True, verbose_name='Email address')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Date joined')),
                ('blocked_status', models.BooleanField(default=False, verbose_name='Blocked status')),
                ('name', models.CharField(max_length=60, null=True, verbose_name='Name')),
                ('surname', models.CharField(max_length=60, null=True, verbose_name='Surname')),
                ('phone_number', models.CharField(max_length=20, null=True, unique=True, verbose_name='Phone number')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ZipCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zipcode', models.CharField(max_length=20, unique=True, verbose_name='Zip code')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zip_code_id', to='users.province')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_block_number', models.CharField(max_length=60, verbose_name='Street block')),
                ('street_floor_number', models.CharField(max_length=60, verbose_name='Street floor')),
                ('street_house_number', models.CharField(max_length=60, verbose_name='Street house number')),
                ('street_name', models.CharField(max_length=60, verbose_name='Street name')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.country')),
                ('province', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.province')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address_id', to='users.user')),
                ('zipcode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.zipcode')),
            ],
        ),
    ]
